name: Node.js CI con Jest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Limpiar dependencias antiguas
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Instalar dependencias
        run: npm install

      - name: Dar permisos a node_modules/.bin
        run: chmod -R +x node_modules/.bin

      - name: Ejecutar pruebas con npx
        run: npx jest
