name: Node.js CI con Jest
on: [push]
jobs:
  test:
      runs-on: ubuntu-lastest
      steps: 
      - name: Clonar repositorio
      uses: actions/checkout@v3
      with:
            node-version: '20'

      - name: Instalar dependencias
      run: npm install

      - name: Ejecutar pruebas
      run: npm test
